### ISSUE TITLE
java.lang.NoSuchMethodError: com.intellij.lang.aspectj.parsing.AjFileParser

### ISSUE THREAD

**Issue by RebortY** [Archinamon/android-gradle-aspectj#69]
I used  Android Studio 3.0  install  aop-common.zip and aspectj.zip
restart Android Studio  get some Exception .

`java.lang.NoSuchMethodError: com.intellij.lang.aspectj.parsing.AjFileParser.parseFile(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/TokenSet;Lcom/intellij/AbstractBundle;Ljava/lang/String;)V
java.lang.RuntimeException: java.lang.NoSuchMethodError: com.intellij.lang.aspectj.parsing.AjFileParser.parseFile(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/TokenSet;Lcom/intellij/AbstractBundle;Ljava/lang/String;)V
	at com.intellij.ide.util.treeView.AbstractTreeUi$54$1.perform(AbstractTreeUi.java:3378)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
	at com.intellij.ide.util.treeView.AbstractTreeBuilder$2.perform(AbstractTreeBuilder.java:467)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:931)
	at com.intellij.ide.util.treeView.AbstractTreeBuilder.runBackgroundLoading(AbstractTreeBuilder.java:464)
	at com.intellij.ide.util.treeView.AbstractTreeUi$54.perform(AbstractTreeUi.java:3333)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.ide.util.treeView.AbstractTreeUi$55.perform(AbstractTreeUi.java:3395)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
	at com.intellij.ide.util.treeView.AbstractTreeUi.lambda$new$0(AbstractTreeUi.java:98)
	at com.intellij.util.concurrency.QueueProcessor.lambda$null$0(QueueProcessor.java:106)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:223)
	at com.intellij.util.concurrency.QueueProcessor.lambda$wrappingProcessor$1(QueueProcessor.java:106)
	at com.intellij.util.concurrency.QueueProcessor.lambda$null$2(QueueProcessor.java:203)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:223)
	at com.intellij.util.concurrency.QueueProcessor.lambda$startProcessing$3(QueueProcessor.java:203)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: com.intellij.lang.aspectj.parsing.AjFileParser.parseFile(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/TokenSet;Lcom/intellij/AbstractBundle;Ljava/lang/String;)V
	at com.intellij.lang.aspectj.parsing.AjFileParser.parse(AjFileParser.java:26)
	at com.intellij.lang.aspectj.psi.stub.AjFileElementType.doParse(AjFileElementType.java:64)
	at com.intellij.lang.aspectj.psi.stub.AjFileElementType.parseContents(AjFileElementType.java:58)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:192)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:240)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:39)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.getFirstChild(SharedImplUtil.java:52)
	at com.intellij.psi.impl.source.PsiFileImpl.getFirstChild(PsiFileImpl.java:847)
	at com.intellij.psi.util.PsiTreeUtil.getChildrenOfType(PsiTreeUtil.java:368)
	at com.intellij.lang.aspectj.psi.impl.PsiAspectJFileImpl.getClasses(PsiAspectJFileImpl.java:28)
	at com.intellij.ide.projectView.impl.ClassesTreeStructureProvider$1.compute(ClassesTreeStructureProvider.java:81)
	at com.intellij.ide.projectView.impl.ClassesTreeStructureProvider$1.compute(ClassesTreeStructureProvider.java:77)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:942)
	at com.intellij.ide.projectView.impl.ClassesTreeStructureProvider.modify(ClassesTreeStructureProvider.java:77)
	at com.intellij.ide.util.treeView.AbstractTreeStructureBase.getChildElements(AbstractTreeStructureBase.java:53)
	at com.intellij.ide.util.treeView.AbstractTreeUi$31.perform(AbstractTreeUi.java:1611)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
	at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1826)
	at com.intellij.ide.util.treeView.AbstractTreeUi.getChildrenFor(AbstractTreeUi.java:1608)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$4500(AbstractTreeUi.java:64)
	at com.intellij.ide.util.treeView.AbstractTreeUi$43.perform(AbstractTreeUi.java:2663)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
	at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1826)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$2500(AbstractTreeUi.java:64)
	at com.intellij.ide.util.treeView.AbstractTreeUi$54$1.perform(AbstractTreeUi.java:3342)`

**Comment by Archinamon** [comment]
Hi! Please, look at my comments where I did describe it:
https://github.com/Archinamon/android-gradle-aspectj/issues/62#issuecomment-340902466

Currently syntax plugin for `.aj` files supports only AS 2.3, not 3.0+.

**Comment by RebortY** [comment]
Oops...  I didn't see it ， tks very much !
